name: java-ci

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Jar file
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt-hotspot

      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
          gradle-version: 7.1.1

      - name: Publish package
        if: success()
        run: gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
